[tool.poetry]
authors = ["m9810223 <m9810223@gmail.com>"]
description = ""
name = "totp"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">3.8,<4"

[tool.poetry.dev-dependencies]
pyotp = "^2.6.0"

[tool.black]
line-length = 120
